### ISSUE TITLE
Consider using wireguardctrl instead of direct genetlink access

### ISSUE THREAD

**Issue by mdlayher** [apognu/wgctl#1]
Hello! I found this repository after checking out your Python experiments the other day.

I notice you're using my netlink/genetlink packages directly, but wanted to make sure you're also aware of: https://github.com/mdlayher/wireguardctrl.

This family of packages deals with the intricacies of the netlink/genetlink handling (large peer message handling on send/receive end), and also provides a unified API that can also deal with userspace devices such as those created by `wireguard-go`.

If you're rolling your own as a way to learn more about the netlink interface and such, I totally understand that, but I would definitely recommend using wireguardctrl if you weren't aware of it already!  If it doesn't meet your needs in some way, feel free to file an issue and I'd be happy to discuss it further.

**Comment by apognu** [comment]
Hi, thanks for your interest.

The first goal was indeed to learn more about netlink, which I feel I have, now.

I have seen your ```wireguardctrl``` repo and have an unpushed branch where I am implementing it for ```wgctl```. It should be ready by tomorrow.

**Comment by apognu** [comment]
All direct dependencies on ```genetlink``` have been removed, using ```wireguardctrl``` fully, except for device creation and routes setup.

**Comment by mdlayher** [comment]
Sounds good.  I don't plan on supporting either of those activities because that means diving into rtnetlink territory, but it looks like you've found a way, which is great.
